//! AXIOM conform — Implementation Conformance Checker
//!
//! Verifies that an implementation produces identical outputs to reference
//! vectors generated by corevec. Compares field-by-field and produces a
//! conformance report.
//!
//! Part of the Interoperability Floor (LAMBDA_CONFORMANCE_CLI_SPEC.md).

use std::path::PathBuf;

use axiom_dmap_vm::AvmInterpreter;
use axiom_dmap_vm::config::AvmConfig;
use axiom_core_logic::execute_core;
use axiom_core_logic::types::{PublicInputs, PublicOutputs, ValidationResult};
use clap::Parser;
use serde::{Serialize, Deserialize};

/// AXIOM conform — Implementation Conformance Checker
#[derive(Parser)]
#[command(name = "conform", about = "Check implementation conformance against reference vectors")]
enum Cli {
    /// Check conformance against a vectors file
    Check {
        /// Path to vectors JSONL file (from corevec)
        #[arg(long)]
        vectors: PathBuf,

        /// Path to axiom-core.elf (if omitted, uses native execution)
        #[arg(long)]
        core_elf: Option<PathBuf>,

        /// Implementation identifier (e.g., "my-validator-v1.0")
        #[arg(long, default_value = "reference")]
        impl_id: String,

        /// Output path for conformance report JSON
        #[arg(long)]
        out: PathBuf,
    },
}

#[derive(Debug, Serialize, Deserialize)]
struct VectorRecord {
    vector_id: String,
    #[serde(default)]
    category: String,
    #[serde(default)]
    description: String,
    input: serde_json::Value,
    expected: VectorExpected,
    #[serde(default)]
    meta: serde_json::Value,
}

#[derive(Debug, Serialize, Deserialize)]
struct VectorExpected {
    core_result: String,
    txid_hex: Option<String>,
    produced_state_id_hex: Option<String>,
    new_balance: Option<u64>,
    #[serde(default)]
    rejection_reason: Option<String>,
}

/// Conformance report (per LAMBDA_CONFORMANCE_CLI_SPEC.md §4)
#[derive(Debug, Serialize)]
struct ConformanceReport {
    impl_id: String,
    vectors_file: String,
    summary: ReportSummary,
    failures: Vec<FailureEntry>,
    meta: ReportMeta,
}

#[derive(Debug, Serialize)]
struct ReportSummary {
    total: u32,
    passed: u32,
    failed: u32,
}

#[derive(Debug, Serialize)]
struct FailureEntry {
    vector_id: String,
    mismatch: Vec<String>,
    expected: serde_json::Value,
    actual: serde_json::Value,
}

#[derive(Debug, Serialize)]
struct ReportMeta {
    tool_id: String,
    tool_version: String,
    checked_at_utc: String,
    execution_mode: String,
}

fn main() {
    let cli = Cli::parse();
    match cli {
        Cli::Check { vectors, core_elf, impl_id, out } => {
            cmd_check(vectors, core_elf, impl_id, out);
        }
    }
}

fn cmd_check(
    vectors_path: PathBuf,
    core_elf: Option<PathBuf>,
    impl_id: String,
    out_path: PathBuf,
) {
    let content = std::fs::read_to_string(&vectors_path)
        .unwrap_or_else(|e| {
            eprintln!("Failed to read {}: {}", vectors_path.display(), e);
            std::process::exit(1);
        });

    // Load AVM once if ELF provided
    let avm = core_elf.as_ref().map(|elf_path| {
        let config = AvmConfig::from_paths(
            elf_path.to_str().unwrap(), None,
        ).unwrap_or_else(|e| {
            eprintln!("Failed to load ELF: {}", e);
            std::process::exit(1);
        });
        AvmInterpreter::new(config.elf_bytes, [0u8; 32])
    });

    let exec_mode = if core_elf.is_some() { "riscv-interpreter" } else { "native" };

    let mut total = 0u32;
    let mut passed = 0u32;
    let mut failures = Vec::new();

    for (i, line) in content.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        // Try parsing as single vector or as part of JSONL
        let record: VectorRecord = match serde_json::from_str(line) {
            Ok(v) => v,
            Err(e) => {
                eprintln!("Line {}: failed to parse vector: {}", i + 1, e);
                continue;
            }
        };

        total += 1;

        // Re-parse the input as PublicInputs
        let inputs: PublicInputs = match serde_json::from_value(record.input.clone()) {
            Ok(v) => v,
            Err(e) => {
                eprintln!("Vector {}: failed to parse input as PublicInputs: {}", record.vector_id, e);
                failures.push(FailureEntry {
                    vector_id: record.vector_id.clone(),
                    mismatch: vec!["input_parse_error".to_string()],
                    expected: serde_json::json!({"error": null}),
                    actual: serde_json::json!({"error": e.to_string()}),
                });
                continue;
            }
        };

        // Execute
        let outputs = if let Some(ref avm) = avm {
            match avm.execute(inputs) {
                Ok(outputs) => outputs,
                Err(e) => {
                    eprintln!("Vector {}: AVM execution error: {}", record.vector_id, e);
                    failures.push(FailureEntry {
                        vector_id: record.vector_id.clone(),
                        mismatch: vec!["execution_error".to_string()],
                        expected: serde_json::json!({"core_result": record.expected.core_result}),
                        actual: serde_json::json!({"error": e.to_string()}),
                    });
                    continue;
                }
            }
        } else {
            execute_core(inputs)
        };

        // Compare
        let mismatches = compare_outputs(&record.expected, &outputs);

        if mismatches.is_empty() {
            passed += 1;
        } else {
            let actual_result = match outputs.result {
                ValidationResult::Accept => "Accept",
                ValidationResult::Reject => "Reject",
                ValidationResult::Fatal => "Fatal",
            };
            let actual_rejection = outputs.rejection_reason.as_ref()
                .map(|r| format!("{:?}", r));

            failures.push(FailureEntry {
                vector_id: record.vector_id.clone(),
                mismatch: mismatches.iter().map(|m| m.0.clone()).collect(),
                expected: serde_json::json!({
                    "core_result": record.expected.core_result,
                    "txid_hex": record.expected.txid_hex,
                    "produced_state_id_hex": record.expected.produced_state_id_hex,
                    "new_balance": record.expected.new_balance,
                    "rejection_reason": record.expected.rejection_reason,
                }),
                actual: serde_json::json!({
                    "core_result": actual_result,
                    "txid_hex": outputs.txid.map(hex::encode),
                    "produced_state_id_hex": outputs.produced_state_id.map(hex::encode),
                    "new_balance": outputs.new_balance,
                    "rejection_reason": actual_rejection,
                }),
            });

            eprintln!("FAIL: {} — mismatched: {:?}", record.vector_id,
                      mismatches.iter().map(|m| &m.0).collect::<Vec<_>>());
        }
    }

    let report = ConformanceReport {
        impl_id: impl_id.clone(),
        vectors_file: vectors_path.display().to_string(),
        summary: ReportSummary { total, passed, failed: total - passed },
        failures,
        meta: ReportMeta {
            tool_id: "axiom-conform".to_string(),
            tool_version: env!("CARGO_PKG_VERSION").to_string(),
            checked_at_utc: chrono::Utc::now().to_rfc3339(),
            execution_mode: exec_mode.to_string(),
        },
    };

    let report_json = serde_json::to_string_pretty(&report).unwrap();
    std::fs::write(&out_path, &report_json)
        .unwrap_or_else(|e| {
            eprintln!("Failed to write {}: {}", out_path.display(), e);
            std::process::exit(1);
        });

    println!("Conformance Report: {}", out_path.display());
    println!("  Implementation: {}", impl_id);
    println!("  Vectors:        {}", total);
    println!("  Passed:         {}", passed);
    println!("  Failed:         {}", total - passed);
    if total == passed {
        println!("  Status:         INTEROPERABLE");
    } else {
        println!("  Status:         NOT INTEROPERABLE ({} mismatches)", total - passed);
        std::process::exit(1);
    }
}

/// Compare expected outputs against actual outputs.
/// Returns list of (field_name, expected_value, actual_value).
fn compare_outputs(expected: &VectorExpected, actual: &PublicOutputs) -> Vec<(String, String, String)> {
    let mut mismatches = Vec::new();

    let actual_result = match actual.result {
        ValidationResult::Accept => "Accept",
        ValidationResult::Reject => "Reject",
        ValidationResult::Fatal => "Fatal",
    };
    if expected.core_result != actual_result {
        mismatches.push((
            "core_result".to_string(),
            expected.core_result.clone(),
            actual_result.to_string(),
        ));
    }

    let actual_txid = actual.txid.map(hex::encode);
    if expected.txid_hex != actual_txid {
        mismatches.push((
            "txid_hex".to_string(),
            format!("{:?}", expected.txid_hex),
            format!("{:?}", actual_txid),
        ));
    }

    let actual_state_id = actual.produced_state_id.map(hex::encode);
    if expected.produced_state_id_hex != actual_state_id {
        mismatches.push((
            "produced_state_id_hex".to_string(),
            format!("{:?}", expected.produced_state_id_hex),
            format!("{:?}", actual_state_id),
        ));
    }

    if expected.new_balance != actual.new_balance {
        mismatches.push((
            "new_balance".to_string(),
            format!("{:?}", expected.new_balance),
            format!("{:?}", actual.new_balance),
        ));
    }

    mismatches
}
