//! Genesis state handling
//!
//! Genesis wallets are the initial state before any funding.
//! Each genesis wallet has:
//! - wallet_seq = 0
//! - balance = 0 (no funds until first funded TX)
//! - A unique genesis_state_id = H("AXIOM_GENESIS" || pk || balance)
//!
//! INVARIANTS (hardcoded in Core):
//! - seq=0: Genesis state. balance=0. No prev_receipts.
//! - seq=1: First funding TX. balance 0→X. No prev_receipts required
//!   (balance was 0, nothing to double-spend). No overlap check.
//!   Validators still witness the funding → receipt for seq=2.
//! - seq=2+: Normal TX. MUST have prev_receipts with 3 witnesses.
//!   Overlap check required.

use crate::crypto::sha3_256_hash;
use crate::types::GenesisWallet;
use alloc::vec::Vec;

/// Compute the genesis_state_id for a wallet
///
/// genesis_state_id = SHA3-256("AXIOM_GENESIS" || public_key || balance)
///
/// This unique ID is consumed by the wallet's first transaction,
/// providing the same double-spend protection as regular state IDs.
pub fn compute_genesis_state_id(public_key: &[u8; 32], balance: u64) -> [u8; 32] {
    let mut data = Vec::new();
    data.extend_from_slice(b"AXIOM_GENESIS");
    data.extend_from_slice(public_key);
    data.extend_from_slice(&balance.to_le_bytes());
    sha3_256_hash(&data)
}

/// Create a genesis wallet (seq=0, balance=0)
pub fn create_genesis_wallet(public_key: [u8; 32], balance: u64) -> GenesisWallet {
    let genesis_state_id = compute_genesis_state_id(&public_key, balance);
    GenesisWallet {
        public_key,
        balance,
        genesis_state_id,
        wallet_seq: 0, // Always 0 for genesis — first funded TX will be seq=1
    }
}

// ============================================================================
// AUTO-GENERATED by genesis-ceremony tool — DO NOT EDIT
// Generated: 2026-04-28
// CA: AXIOM Origin (PGP: 4A18 9E40 F20F 5A34 B7D6  9F19 D596 AB09 93DF F9D2)
// ============================================================================
/// Genesis validators - hardcoded in Core.bin
///
/// These are the SPHINCS+ public keys of the 10 Genesis validators (First Penguins).
/// They define the "reality anchor" - the root of trust for all VBCs.
/// A VBC chain is valid if and only if all branches terminate at one of these keys.
/// Used for backward-compatible overlap detection.
/// VBC chain verification uses ROOT_AUTHORITY_PKS as trust anchor.
pub const GENESIS_VALIDATORS: [[u8; 32]; 10] = [
    // axiom-first-penguin-alpha
    [
        0x2B, 0xA3, 0xCE, 0xCC, 0x50, 0x47, 0xF8, 0x99,
        0x69, 0x9F, 0xAA, 0xE0, 0xE5, 0x60, 0x3A, 0x9D,
        0x81, 0xF1, 0x77, 0x3C, 0x6A, 0x06, 0x95, 0x67,
        0xE9, 0x22, 0x4C, 0x68, 0xF0, 0xB5, 0x08, 0xF6,
    ],
    // axiom-first-penguin-beta
    [
        0x62, 0x54, 0x50, 0xB3, 0x9B, 0xCD, 0x43, 0x0B,
        0xD8, 0xFD, 0x5A, 0xB3, 0xBC, 0x84, 0xC6, 0x3B,
        0x8A, 0x67, 0x2B, 0xF8, 0x77, 0x78, 0xE0, 0x3C,
        0xBD, 0xA0, 0xBC, 0xF5, 0x53, 0x5C, 0x3A, 0xFF,
    ],
    // axiom-first-penguin-gamma
    [
        0x62, 0x8E, 0x97, 0x2D, 0xDF, 0x10, 0xC5, 0x54,
        0x38, 0x7C, 0xEA, 0x5E, 0xEC, 0x32, 0x9E, 0x04,
        0x36, 0x61, 0x09, 0x32, 0x9E, 0x26, 0x6B, 0xCD,
        0xB5, 0xE8, 0x6F, 0xF4, 0xC7, 0xA3, 0x31, 0x31,
    ],
    // axiom-first-penguin-delta
    [
        0xA1, 0x4A, 0x3C, 0xCB, 0x7F, 0x65, 0x48, 0x53,
        0x41, 0xC8, 0xD3, 0x46, 0x47, 0x89, 0xB7, 0x16,
        0xB9, 0x19, 0x74, 0xC4, 0xA3, 0xA8, 0x9B, 0xFF,
        0x32, 0xDA, 0xFA, 0x6C, 0x6F, 0x88, 0x7D, 0xD1,
    ],
    // axiom-first-penguin-epsilon
    [
        0x6D, 0x6B, 0x83, 0x76, 0xC5, 0x07, 0x21, 0x4E,
        0x37, 0x50, 0x51, 0xD3, 0xEA, 0x30, 0x82, 0x4D,
        0x68, 0xC5, 0x83, 0x0A, 0xD0, 0x8E, 0x24, 0xF1,
        0xE0, 0x7A, 0x72, 0x6E, 0x1A, 0x95, 0x68, 0xE7,
    ],
    // axiom-first-penguin-zeta
    [
        0x92, 0x44, 0x9F, 0xE6, 0xE5, 0x40, 0x48, 0xC7,
        0xD0, 0xF5, 0x75, 0x86, 0xDA, 0x66, 0xB2, 0xBA,
        0x68, 0xD8, 0x73, 0x4E, 0x9C, 0x5E, 0x23, 0x2D,
        0x11, 0xF8, 0x56, 0x80, 0xA5, 0x3A, 0x1C, 0x8B,
    ],
    // axiom-first-penguin-eta
    [
        0x40, 0x9F, 0x2C, 0xAE, 0xA3, 0x15, 0xC7, 0xF1,
        0xDB, 0xBD, 0xD4, 0x7E, 0xA5, 0xE5, 0xB6, 0xF0,
        0x1F, 0x5E, 0x1D, 0x4A, 0xAC, 0x04, 0xF7, 0x78,
        0xA8, 0x93, 0xA2, 0x7D, 0x8A, 0x26, 0x27, 0x20,
    ],
    // axiom-first-penguin-theta
    [
        0x93, 0xE6, 0xFB, 0x6A, 0xD0, 0x17, 0x2E, 0xB5,
        0x58, 0xFF, 0x10, 0x46, 0xAB, 0x65, 0x2F, 0x0A,
        0xAC, 0x75, 0xCF, 0x46, 0x3D, 0x2C, 0x22, 0xD6,
        0x77, 0x2E, 0xDA, 0xE9, 0x6C, 0x2A, 0xBF, 0xD9,
    ],
    // axiom-first-penguin-iota
    [
        0xB5, 0x2B, 0x40, 0x50, 0xD3, 0x29, 0xC6, 0x4C,
        0x1E, 0xFB, 0x29, 0x7A, 0x1E, 0x1C, 0xCB, 0x57,
        0xB0, 0xFB, 0xD1, 0x07, 0xB7, 0x31, 0xDC, 0x3E,
        0x36, 0x68, 0xD8, 0x07, 0xE7, 0xD4, 0xB0, 0x8E,
    ],
    // axiom-first-penguin-kappa
    [
        0xBD, 0x6A, 0x58, 0x9F, 0xF5, 0x78, 0x1C, 0x34,
        0x23, 0xA6, 0x22, 0xE6, 0xA1, 0x27, 0x09, 0x99,
        0x71, 0x64, 0xD5, 0xEB, 0x0E, 0xD4, 0x8C, 0x96,
        0x99, 0xBB, 0x88, 0x32, 0x69, 0x2F, 0xC8, 0xB5,
    ],
];

/// Root Authority SPHINCS+ public keys — the trust anchor of AXIOM.
/// Chain verification stops when it hits one of these.
/// Certificate Authority: AXIOM Origin
/// PGP: 4A18 9E40 F20F 5A34 B7D6  9F19 D596 AB09 93DF F9D2
pub const ROOT_AUTHORITY_PKS: [[u8; 32]; 3] = [
    // ROOT_1
    [
        0x3E, 0x4F, 0x50, 0x98, 0xEC, 0x82, 0x77, 0x93,
        0xC7, 0xB0, 0xF7, 0x2E, 0xC7, 0x9E, 0x46, 0x2C,
        0xD5, 0x3F, 0x73, 0x37, 0x6B, 0xB4, 0xF3, 0x8D,
        0x98, 0x32, 0x92, 0x7E, 0xFD, 0x4A, 0x1A, 0xEF,
    ],
    // ROOT_2
    [
        0x60, 0xAF, 0x6E, 0x17, 0x4A, 0x3B, 0x35, 0x17,
        0x7B, 0x93, 0xB5, 0x15, 0x95, 0x46, 0x5E, 0xE9,
        0xC5, 0x40, 0x28, 0x68, 0x05, 0xD1, 0x49, 0x68,
        0x9B, 0x2F, 0xA2, 0x89, 0x19, 0x89, 0x57, 0x14,
    ],
    // ROOT_3
    [
        0x54, 0x9A, 0x72, 0x77, 0x57, 0xC9, 0xE0, 0x3F,
        0x05, 0x52, 0x87, 0xF5, 0xF2, 0xDA, 0x46, 0x43,
        0x30, 0xEF, 0x24, 0x04, 0xCA, 0xE0, 0x88, 0xE5,
        0xCA, 0xF2, 0xEC, 0xDC, 0x12, 0x6C, 0x00, 0x5D,
    ],
];

/// Certificate Authority PGP fingerprint (20 bytes)
/// 4A18 9E40 F20F 5A34 B7D6  9F19 D596 AB09 93DF F9D2
pub const CA_PGP_FINGERPRINT: [u8; 20] = [
    0x4A, 0x18, 0x9E, 0x40, 0xF2, 0x0F, 0x5A, 0x34, 0xB7, 0xD6, 0x9F, 0x19, 0xD5, 0x96, 0xAB, 0x09, 0x93, 0xDF, 0xF9, 0xD2
];

/// Check if a public key is a root authority key
pub fn is_root_authority(pk: &[u8]) -> bool {
    if pk.len() != 32 {
        return false;
    }
    let pk_array: [u8; 32] = pk.try_into().unwrap_or([0; 32]);
    // Skip all-zero placeholder keys
    if pk_array == [0u8; 32] {
        return false;
    }
    ROOT_AUTHORITY_PKS.iter().any(|r| r == &pk_array)
}

/// Check if a public key is a genesis validator
pub fn is_genesis_validator(pk: &[u8]) -> bool {
    if pk.len() != 32 {
        return false;
    }
    
    let pk_array: [u8; 32] = pk.try_into().unwrap_or([0; 32]);
    GENESIS_VALIDATORS.iter().any(|g| g == &pk_array)
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_compute_genesis_state_id() {
        let pk = [0x42u8; 32];
        let balance = 1_000_000_000_000u64; // 1 trillion atoms
        
        let state_id = compute_genesis_state_id(&pk, balance);
        
        // Should be deterministic
        let state_id_2 = compute_genesis_state_id(&pk, balance);
        assert_eq!(state_id, state_id_2);
        
        // Different balance should give different state_id
        let state_id_3 = compute_genesis_state_id(&pk, balance + 1);
        assert_ne!(state_id, state_id_3);
        
        // Different pk should give different state_id
        let pk2 = [0x43u8; 32];
        let state_id_4 = compute_genesis_state_id(&pk2, balance);
        assert_ne!(state_id, state_id_4);
    }
    
    #[test]
    fn test_create_genesis_wallet() {
        let pk = [0x42u8; 32];
        let balance = 1_000_000_000_000u64;
        
        let wallet = create_genesis_wallet(pk, balance);
        
        assert_eq!(wallet.public_key, pk);
        assert_eq!(wallet.balance, balance);
        assert_eq!(wallet.wallet_seq, 0);
        assert_eq!(
            wallet.genesis_state_id,
            compute_genesis_state_id(&pk, balance)
        );
    }
    
    #[test]
    fn test_is_genesis_validator() {
        // All 10 genesis validators should be recognized
        for gv in &GENESIS_VALIDATORS {
            assert!(is_genesis_validator(gv));
        }

        // Non-genesis key
        let other = [0xFFu8; 32];
        assert!(!is_genesis_validator(&other));

        // Wrong length
        let short = [0x01u8; 16];
        assert!(!is_genesis_validator(&short));
    }

    // Nabla root authority and genesis validator tests moved to nabla_genesis.rs
}
