//! wallet_id validation (YPX-007: Receiver-Defined Security Level)
//!
//! wallet_id format: "email/hex10" where hex10 = checksum(6) + pk_bind(2) + salt(2)
//! checksum = first_6_hex(BLAKE3(email || wallet_identity_key || salt || k_byte || proof_type_byte))
//! pk_bind = first_2_hex(BLAKE3("AXIOM_PK_BIND" || email || WALLET_IDENTITY_KEY || pk || salt || k || pt))
//!
//! Each wallet has 7 addresses (one per security level). Core extracts (k, proof_type)
//! from the checksum by trying all 7 combinations. The sender cannot choose or override
//! the security level — it is baked into the address itself.
//!
//! Example: "bob@example.com/a3f7b2ff32"
//!   - email: "bob@example.com"
//!   - checksum: "a3f7b2" (6 hex chars)
//!   - pk_bind: "ff" (2 hex chars, binds wallet to owner's Ed25519 pk)
//!   - salt: "32" (2 hex chars)
//!
//! This is for ANTI-TYPO protection + security level enforcement:
//!   - User types "bob@gmial.com/a3f7b232" (typo in gmail)
//!   - Checksum won't match → REJECT
//!   - Money NOT sent to wrong person!
//!
//! The wallet_identity_key is semi-public (extractable from core-logic)
//! but that's fine - security comes from signatures + consensus,
//! not from the checksum.
//!
//! SECURITY (C2): All email strings are normalized to:
//!   - Lowercase (ASCII only)
//!   - Trimmed whitespace
//!   - ASCII-only validation (rejects non-ASCII to prevent homoglyph attacks)

// CONSENSUS_CRITICAL

use crate::crypto::blake3_hash;
use crate::errors::CoreResult;
use crate::types::ValidationError;
use alloc::format;
use alloc::string::String;
use alloc::vec::Vec;

// === YPX-007: Security Level Constants ===

/// k encoding — number of validators required
pub const K_ARK: u8 = 0;
pub const K_MIN: u8 = 3;
pub const K_DEFAULT: u8 = 3;
pub const K_MAX: u8 = 5;

/// proof_type encoding — matches ProofType enum in core/avm/src/dmap/mod.rs
pub const PROOF_TYPE_ZKP: u8 = 0;
pub const PROOF_TYPE_DMAP: u8 = 1;
pub const PROOF_TYPE_ARK: u8 = 2;

/// All 7 (k_byte, proof_type_byte, display_name) combinations.
/// Order matters: this is the iteration order for extract_security_level().
pub const WALLET_ID_PARAMS: [(u8, u8, &str); 7] = [
    (K_ARK, PROOF_TYPE_ARK, "Ark"),
    (3, PROOF_TYPE_DMAP, "Standard"),
    (3, PROOF_TYPE_ZKP, "A+"),
    (4, PROOF_TYPE_DMAP, "Secure"),
    (4, PROOF_TYPE_ZKP, "Secure+"),
    (5, PROOF_TYPE_DMAP, "AAA"),
    (5, PROOF_TYPE_ZKP, "AAA+"),
];

/// S-ABR overlap: strict majority floor(k/2) + 1.
/// Prevents double-spend — attacker cannot present conflicting TX to fresh validators.
pub fn sabr_overlap(k: u8) -> u8 {
    if k == 0 { return 0; }
    (k / 2) + 1
}

/// Wallet identity key embedded at compile time.
/// This is the network identity — defines which wallet addresses are valid.
/// Used for wallet_id checksum computation and FACT #0 signature verification.
///
/// NOTE: This is NOT secret - it's intentionally semi-public.
/// It only enables checksum verification for anti-typo protection.
/// Security comes from signatures and k=3 consensus.
///
/// ╔══════════════════════════════════════════════════════════════════╗
/// ║  WARNING: DEV/TESTNET KEY — DO NOT SHIP TO MAINNET             ║
/// ║                                                                 ║
/// ║  Generated by g1-full-ceremony.sh (2026-03-27) for development  ║
/// ║  and testnet use ONLY. This key is baked into all dev VBCs/NBCs ║
/// ║  and wallet identities. It is NOT secret — anyone who reads     ║
/// ║  this source knows it.                                          ║
/// ║                                                                 ║
/// ║  MAINNET LAUNCH REQUIRES:                                       ║
/// ║    1. Run g1-full-ceremony.sh with production keys              ║
/// ║    2. The ceremony replaces this constant with fresh bytes       ║
/// ║    3. The compile guard below blocks release builds until        ║
/// ║       this constant no longer matches 0xb0,0xf7 (dev prefix)    ║
/// ║    4. All binaries must be rebuilt after ceremony                ║
/// ╚══════════════════════════════════════════════════════════════════╝
pub const WALLET_IDENTITY_KEY: [u8; 32] = [
    0xb0, 0xf7, 0xac, 0x62, 0xaf, 0x24, 0x97, 0xc7,
    0x8b, 0x64, 0x88, 0x4a, 0x6d, 0x40, 0x21, 0xf8,
    0xdc, 0x41, 0x8a, 0xe4, 0x58, 0x13, 0x52, 0xb8,
    0x39, 0x95, 0xd2, 0x19, 0x05, 0xb9, 0xb2, 0x7b,
];

// Compile guard: RELEASE builds FAIL if WALLET_IDENTITY_KEY still has the
// dev/testnet value (0xb0, 0xf7 prefix). The mainnet ceremony replaces
// this key, which changes the prefix, which unblocks the guard.
// Disabled by `dev-mode` feature so dev/testnet builds still work.
#[cfg(all(not(feature = "dev-mode"), not(debug_assertions)))]
const _: () = {
    assert!(
        WALLET_IDENTITY_KEY[0] != 0xb0 || WALLET_IDENTITY_KEY[1] != 0xf7,
        "WALLET_IDENTITY_KEY is still the dev/testnet key — run mainnet ceremony before release build"
    );
};

/// Normalize an email address for consistent checksum computation.
/// 
/// SECURITY (C2 - Semantic Confusion Prevention):
/// - Converts to lowercase (ASCII only)
/// - Trims whitespace
/// - Rejects non-ASCII characters (prevents homoglyph attacks like "аlice" vs "alice")
/// 
/// This ensures the same email is always hashed the same way,
/// preventing field aliasing attacks where different representations
/// of the "same" email produce different checksums.
fn normalize_email(email: &str) -> CoreResult<String> {
    let trimmed = email.trim();
    
    // Reject empty email
    if trimmed.is_empty() {
        return Err(ValidationError::MalformedAddress);
    }
    
    // SECURITY: Reject non-ASCII characters
    // This prevents homoglyph attacks where Cyrillic 'а' looks like Latin 'a'
    // Example attack: "аlice@test.com" (Cyrillic а) vs "alice@test.com" (Latin a)
    if !trimmed.is_ascii() {
        return Err(ValidationError::MalformedAddress);
    }
    
    // Convert to lowercase for consistency
    Ok(trimmed.to_ascii_lowercase())
}

/// Strip encryption suffix (-P, -G, etc.) from a wallet_id.
/// "bob@example.com/a3f7b2ff32-P" → "bob@example.com/a3f7b2ff32"
pub fn strip_encryption_suffix(wallet_id: &str) -> String {
    // Suffixes: -P (PGP), -G (GPG). Always at the very end after hex10.
    if wallet_id.ends_with("-P") || wallet_id.ends_with("-G") {
        String::from(&wallet_id[..wallet_id.len() - 2])
    } else {
        String::from(wallet_id)
    }
}

/// Strip email change suffix (-01, -02, ..., -99) from wallet_id.
/// Returns (clean_wallet_id, change_count). change_count = None if no suffix.
///
/// Format: "email/hex10-XX" where XX is 01-99.
/// Only matches if the part before -XX ends with 10 hex chars after the last '/'.
/// Stripped AFTER encryption suffix: "email/hex10-01-P" → strip -P → strip -01.
pub fn strip_email_change_suffix(wallet_id: &str) -> (String, Option<u8>) {
    let s = wallet_id;
    if s.len() < 3 {
        return (String::from(s), None);
    }

    // The valid "-XX" suffix is exactly 3 ASCII bytes. If `len - 3` is not a
    // char boundary, the tail is a multi-byte UTF-8 char (e.g. a 4-byte emoji)
    // and cannot be a suffix — return safely instead of panicking on a mid-char
    // byte slice. DoS fix: a hostile wallet_id (e.g. a receiver_wallet_id inside
    // a TX) ending in a multi-byte char must NEVER unwind Core. The decoder
    // fails closed (no suffix), never panics.
    let cut = s.len() - 3;
    if !s.is_char_boundary(cut) {
        return (String::from(s), None);
    }
    let last3 = &s[cut..];
    if !last3.starts_with('-') {
        return (String::from(s), None);
    }

    let digits = &last3[1..];
    if digits.len() != 2 || !digits.chars().all(|c| c.is_ascii_digit()) {
        return (String::from(s), None);
    }

    let n: u8 = match digits.parse() {
        Ok(n) if n >= 1 => n,
        _ => return (String::from(s), None),
    };

    // Verify the part before -XX has a valid hex10 structure:
    // Must have exactly 10 hex chars after the last '/' (with optional dashes for display)
    // `cut` is the verified char boundary at len-3 (see above) — safe to slice.
    let base = &s[..cut];
    if let Some(slash_pos) = base.rfind('/') {
        let hex_part = &base[slash_pos + 1..];
        let hex_clean: String = hex_part.chars().filter(|c| *c != '-').collect();
        if hex_clean.len() == 10 && hex_clean.chars().all(|c| c.is_ascii_hexdigit()) {
            return (String::from(base), Some(n));
        }
    }

    (String::from(s), None)
}

/// Check if a wallet_id requires receiver_address (has -XX email change suffix).
pub fn requires_receiver_address(wallet_id: &str) -> bool {
    let clean = strip_encryption_suffix(wallet_id);
    let (_, change) = strip_email_change_suffix(&clean);
    change.is_some()
}

/// Parse a wallet_id into (email, checksum, pk_bind, salt)
///
/// wallet_id format: "email/hex10" or "email/hex10-P" (encryption suffix stripped)
/// hex10 = checksum(6) + pk_bind(2) + salt(2)
/// Example: "bob@example.com/a3f7b2ff32" → ("bob@example.com", "a3f7b2", "ff", "32")
///
/// checksum(6): anti-typo + security level extraction (BLAKE3, no pk)
/// pk_bind(2): identity binding (BLAKE3 with pk)
/// salt(2): random salt
///
/// SECURITY: Email is normalized before returning.
pub fn parse_wallet_id(wallet_id: &str) -> CoreResult<(String, String, String, String)> {
    // Strip suffixes: -P (encryption), then -XX (email change)
    let after_pgp = strip_encryption_suffix(wallet_id);
    let (clean, _) = strip_email_change_suffix(&after_pgp);

    // Find the last '/' separator
    let slash_pos = clean
        .rfind('/')
        .ok_or(ValidationError::MalformedAddress)?;

    let email_raw = &clean[..slash_pos];
    let hex_part = &clean[slash_pos + 1..];

    // Normalize email (lowercase, trim, ASCII-only)
    let email = normalize_email(email_raw)?;

    // Validate email contains @
    if !email.contains('@') {
        return Err(ValidationError::MalformedAddress);
    }

    // Clean hex part (remove dashes if any)
    let hex_clean: String = hex_part
        .chars()
        .filter(|c| *c != '-')
        .collect();

    // Must be exactly 10 hex chars (checksum6 + pk_bind2 + salt2)
    if hex_clean.len() != 10 {
        return Err(ValidationError::MalformedAddress);
    }

    // Validate all chars are hex
    if !hex_clean.chars().all(|c| c.is_ascii_hexdigit()) {
        return Err(ValidationError::MalformedAddress);
    }

    let checksum = hex_clean[0..6].to_lowercase();
    let pk_bind = hex_clean[6..8].to_lowercase();
    let salt = hex_clean[8..10].to_lowercase();

    Ok((email, checksum, pk_bind, salt))
}

/// Extract email from wallet_id
///
/// "bob@example.com/a3f7b2ff32" → "bob@example.com"
pub fn extract_email(wallet_id: &str) -> CoreResult<String> {
    let (email, _, _, _) = parse_wallet_id(wallet_id)?;
    Ok(email)
}

/// Compute the anti-typo checksum for a wallet_id (no pk — k extraction at CL1).
/// YPX-007: checksum = BLAKE3(email || MASTER_PK_hex || salt || k_byte || proof_type_byte)[0..3]
///
/// This checksum does NOT include pk — it's for anti-typo + security level extraction.
/// pk binding is done via a separate pk_bind byte (see compute_pk_bind).
fn compute_checksum(email: &str, salt: &str, master_pk: &[u8; 32], k_byte: u8, proof_type_byte: u8) -> String {
    let mut data = email.as_bytes().to_vec();
    data.extend_from_slice(hex::encode(master_pk).as_bytes());
    data.extend_from_slice(salt.as_bytes());
    data.push(k_byte);
    data.push(proof_type_byte);

    let hash = blake3_hash(&data);
    hex::encode(&hash[0..3])
}

/// Compute pk binding byte for a wallet_id.
/// pk_bind = BLAKE3("AXIOM_PK_BIND" || email || MASTER_PK || pk || salt || k || pt)[0..1] (2 hex chars)
///
/// This binds the wallet_id to the owner's Ed25519 public key.
/// Verified at CL5 to prevent cheque theft — only the pk that generated
/// the wallet_id can redeem cheques addressed to it.
fn compute_pk_bind(email: &str, salt: &str, master_pk: &[u8; 32], pk: &[u8; 32], k_byte: u8, proof_type_byte: u8) -> String {
    let mut data = b"AXIOM_PK_BIND".to_vec();
    data.extend_from_slice(email.as_bytes());
    data.extend_from_slice(master_pk);
    data.extend_from_slice(pk);
    data.extend_from_slice(salt.as_bytes());
    data.push(k_byte);
    data.push(proof_type_byte);

    let hash = blake3_hash(&data);
    hex::encode(&hash[0..1])
}

/// Compute checksum using wallet_secret + pk (no WALLET_IDENTITY_KEY needed).
/// YP §31.9: checksum = BLAKE3(email || wallet_secret || pk_hex || salt || k_byte || pt_byte)[0..3]
fn compute_checksum_with_secret(
    email: &str, salt: &str, wallet_secret: &[u8; 32], pk: &[u8; 32],
    k_byte: u8, proof_type_byte: u8,
) -> String {
    let mut data = email.as_bytes().to_vec();
    data.extend_from_slice(wallet_secret);
    data.extend_from_slice(hex::encode(pk).as_bytes());
    data.extend_from_slice(salt.as_bytes());
    data.push(k_byte);
    data.push(proof_type_byte);
    let hash = blake3_hash(&data);
    hex::encode(&hash[0..3])
}

/// Generate a wallet_id using wallet_secret (no WALLET_IDENTITY_KEY).
pub fn generate_wallet_id_with_secret(
    email: &str, salt: &str, wallet_secret: &[u8; 32], pk: &[u8; 32],
) -> CoreResult<String> {
    generate_wallet_id_with_secret_full(email, salt, wallet_secret, pk, K_DEFAULT, PROOF_TYPE_DMAP)
}

/// Generate a wallet_id with explicit security level using wallet_secret.
/// Format: "email/checksum(6) + pk_bind(2) + salt(2)" = hex10
/// checksum from wallet_secret path, pk_bind from WALLET_IDENTITY_KEY + pk.
pub fn generate_wallet_id_with_secret_full(
    email: &str, salt: &str, wallet_secret: &[u8; 32], pk: &[u8; 32],
    k_byte: u8, proof_type_byte: u8,
) -> CoreResult<String> {
    let normalized_email = normalize_email(email)?;
    // char-boundary-safe: `get` yields None on a short or mid-char index → "00".
    let salt_clean = salt.get(0..2).unwrap_or("00");
    let checksum = compute_checksum_with_secret(
        &normalized_email, salt_clean, wallet_secret, pk, k_byte, proof_type_byte,
    );
    let pk_bind = compute_pk_bind(
        &normalized_email, salt_clean, &WALLET_IDENTITY_KEY, pk, k_byte, proof_type_byte,
    );
    Ok(format!("{}/{}{}{}", normalized_email, checksum, pk_bind, salt_clean))
}

/// Generate all 7 wallet_ids using wallet_secret.
pub fn generate_all_wallet_ids_with_secret(
    email: &str, salt: &str, wallet_secret: &[u8; 32], pk: &[u8; 32],
) -> CoreResult<Vec<(String, u8, u8, &'static str)>> {
    let mut result = Vec::with_capacity(7);
    for &(k_byte, pt_byte, name) in &WALLET_ID_PARAMS {
        let wid = generate_wallet_id_with_secret_full(
            email, salt, wallet_secret, pk, k_byte, pt_byte,
        )?;
        result.push((wid, k_byte, pt_byte, name));
    }
    Ok(result)
}

/// Verify a wallet_id was generated with a specific wallet_secret and pk.
/// Returns (k, proof_type) if match. Used by CL5 for wallet ownership proof.
pub fn verify_wallet_id_with_secret(
    wallet_id: &str, wallet_secret: &[u8; 32], pk: &[u8; 32],
) -> CoreResult<(u8, u8)> {
    let (email, checksum, _pk_bind, salt) = parse_wallet_id(wallet_id)?;
    for &(k_byte, pt_byte, _name) in &WALLET_ID_PARAMS {
        let candidate = compute_checksum_with_secret(
            &email, &salt, wallet_secret, pk, k_byte, pt_byte,
        );
        if checksum == candidate.to_lowercase() {
            return Ok((k_byte, pt_byte));
        }
    }
    Err(ValidationError::InvalidWalletId)
}

/// Validate a wallet_id checksum (anti-typo + k extraction).
///
/// Verifies the checksum matches for some (k, pt) combination.
/// Does NOT verify pk_bind — use verify_pk_binding for that.
///
/// Encryption suffixes (-P, -G) are stripped before validation.
pub fn validate_wallet_id(wallet_id: &str) -> CoreResult<()> {
    extract_security_level(wallet_id).map(|_| ())
}

/// Extract (k, proof_type) from a wallet_id by trying all 7 combinations.
///
/// YPX-007: Core extracts the security level from the address — the sender
/// does not choose it. 7 BLAKE3 hashes is trivial (~1μs total).
///
/// Uses the checksum (first 6 hex) which does NOT include pk.
/// pk binding is verified separately via verify_pk_binding().
///
/// Returns (k, proof_type) on success, Err(InvalidWalletId) if no match.
pub fn extract_security_level(wallet_id: &str) -> CoreResult<(u8, u8)> {
    // Strip suffixes: -P (encryption), then -XX (email change) before checksum validation
    let after_pgp = strip_encryption_suffix(wallet_id);
    let (clean_id, _) = strip_email_change_suffix(&after_pgp);
    extract_security_level_with_identity_key(&clean_id, &WALLET_IDENTITY_KEY)
}

/// Extract (k, proof_type) with a specific identity key (for testing)
pub fn extract_security_level_with_identity_key(
    wallet_id: &str,
    master_pk: &[u8; 32],
) -> CoreResult<(u8, u8)> {
    let (email, checksum, _pk_bind, salt) = parse_wallet_id(wallet_id)?;

    for &(k_byte, pt_byte, _name) in &WALLET_ID_PARAMS {
        let candidate = compute_checksum(&email, &salt, master_pk, k_byte, pt_byte);
        if checksum == candidate.to_lowercase() {
            return Ok((k_byte, pt_byte));
        }
    }

    Err(ValidationError::InvalidWalletId)
}

/// FACT class isolation: true iff this wallet_id belongs to the dev
/// class (`AXIOM_DESIGN_FactClassIsolation.md` §7).
///
/// The dev class is signalled by an exact `@axiom.internal` email
/// domain. ICANN reserves `.internal` for private/internal-network
/// use, so it cannot clash with any public domain.
///
/// Match is strict and case-insensitive on the domain only:
/// - `developer@axiom.internal` → true
/// - `alice@axiom.com` → false
/// - `bob@axiom.internal.foo` → false
/// - `charlie@axiom` → false
pub fn is_dev_wallet(wallet_id: &str) -> bool {
    let after_pgp = strip_encryption_suffix(wallet_id);
    let (clean, _) = strip_email_change_suffix(&after_pgp);
    let email = clean.split('/').next().unwrap_or("");
    let mut parts = email.splitn(2, '@');
    let _local = parts.next();
    let domain = parts.next().unwrap_or("").to_ascii_lowercase();
    domain == "axiom.internal"
}

/// FACT class isolation rule R1
/// (`AXIOM_DESIGN_FactClassIsolation.md` §2.1, §3).
///
/// A transaction is valid only if sender and recipient share the same
/// class. Either both are dev (`@axiom.internal`) or neither is.
/// Symmetric: blocks `dev -> public` and `public -> dev` equally —
/// no one-way valve (silent-burn argument, design §3).
///
/// Protocol addresses (BURN / DEED / FEE / DWP) are exempt — they're
/// not real wallets and have no class. A dev wallet must remain able
/// to burn dev-AXC; a public wallet must remain able to burn AXC.
pub fn check_domain_isolation(
    sender_wallet_id: &str,
    recipient_wallet_id: &str,
) -> CoreResult<()> {
    let is_protocol = |w: &str| {
        w == crate::types::BURN_ADDRESS
            || w == crate::types::DEED_ADDRESS
            || w == crate::types::FEE_ADDRESS
            || w.starts_with(crate::types::DWP_ADDRESS_PREFIX)
    };
    if is_protocol(sender_wallet_id) || is_protocol(recipient_wallet_id) {
        return Ok(());
    }
    if is_dev_wallet(sender_wallet_id) != is_dev_wallet(recipient_wallet_id) {
        return Err(ValidationError::DomainMismatch);
    }
    Ok(())
}

/// Verify that a wallet_id's pk_bind byte matches the given public key.
///
/// This is the CL5 identity binding check. The pk_bind (2 hex chars at positions 6-7)
/// is a BLAKE3 hash of email + MASTER_PK + pk + salt + k + pt. Only the owner's pk
/// produces the correct pk_bind.
///
/// Call extract_security_level first to get (k, pt), then verify_pk_binding with pk.
pub fn verify_pk_binding(wallet_id: &str, pk: &[u8; 32]) -> CoreResult<()> {
    let after_pgp = strip_encryption_suffix(wallet_id);
    let (clean_id, _) = strip_email_change_suffix(&after_pgp);
    verify_pk_binding_with_identity_key(&clean_id, &WALLET_IDENTITY_KEY, pk)
}

/// Verify pk binding with a specific identity key (for testing).
pub fn verify_pk_binding_with_identity_key(
    wallet_id: &str,
    master_pk: &[u8; 32],
    pk: &[u8; 32],
) -> CoreResult<()> {
    let (email, _checksum, pk_bind, salt) = parse_wallet_id(wallet_id)?;

    // Try all 7 (k, pt) combinations — pk_bind must match for at least one
    for &(k_byte, pt_byte, _name) in &WALLET_ID_PARAMS {
        let candidate = compute_pk_bind(&email, &salt, master_pk, pk, k_byte, pt_byte);
        if pk_bind == candidate.to_lowercase() {
            return Ok(());
        }
    }

    Err(ValidationError::InvalidWalletId)
}

/// Generate a wallet_id for an email with a given salt and pk (defaults to Standard: k=3, dmap)
///
/// Returns full wallet_id: "email/hex10" where hex10 = checksum(6) + pk_bind(2) + salt(2)
/// pk is bound via pk_bind for CL5 identity verification (prevents cheque theft).
///
/// SECURITY: Email is normalized before checksum computation.
pub fn generate_wallet_id(email: &str, salt: &str, pk: &[u8; 32]) -> CoreResult<String> {
    generate_wallet_id_with_identity_key(email, salt, &WALLET_IDENTITY_KEY, pk)
}

/// Generate a wallet_id with a specific identity key (defaults to Standard: k=3, dmap)
pub fn generate_wallet_id_with_identity_key(
    email: &str,
    salt: &str,
    master_pk: &[u8; 32],
    pk: &[u8; 32],
) -> CoreResult<String> {
    generate_wallet_id_full(email, salt, master_pk, pk, K_DEFAULT, PROOF_TYPE_DMAP)
}

/// Generate a wallet_id with explicit security level parameters.
/// Format: "email/checksum(6) + pk_bind(2) + salt(2)"
pub fn generate_wallet_id_full(
    email: &str,
    salt: &str,
    master_pk: &[u8; 32],
    pk: &[u8; 32],
    k_byte: u8,
    proof_type_byte: u8,
) -> CoreResult<String> {
    let normalized_email = normalize_email(email)?;

    // char-boundary-safe: `get` yields None on a short or mid-char index → "00".
    let salt_clean = salt.get(0..2).unwrap_or("00");

    let checksum = compute_checksum(&normalized_email, salt_clean, master_pk, k_byte, proof_type_byte);
    let pk_bind = compute_pk_bind(&normalized_email, salt_clean, master_pk, pk, k_byte, proof_type_byte);
    Ok(format!("{}/{}{}{}", normalized_email, checksum, pk_bind, salt_clean))
}

/// YPX-007: Generate all 7 wallet_ids for a wallet.
///
/// Returns Vec of (wallet_id, k, proof_type, display_name).
/// All 7 share the same email+salt but have different checksums and pk_binds.
pub fn generate_all_wallet_ids(email: &str, salt: &str, pk: &[u8; 32]) -> CoreResult<Vec<(String, u8, u8, &'static str)>> {
    generate_all_wallet_ids_with_identity_key(email, salt, &WALLET_IDENTITY_KEY, pk)
}

/// Generate all 7 wallet_ids with a specific identity key (for testing)
pub fn generate_all_wallet_ids_with_identity_key(
    email: &str,
    salt: &str,
    master_pk: &[u8; 32],
    pk: &[u8; 32],
) -> CoreResult<Vec<(String, u8, u8, &'static str)>> {
    let mut result = Vec::with_capacity(7);
    for &(k_byte, pt_byte, name) in &WALLET_ID_PARAMS {
        let wid = generate_wallet_id_full(email, salt, master_pk, pk, k_byte, pt_byte)?;
        result.push((wid, k_byte, pt_byte, name));
    }
    Ok(result)
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_parse_wallet_id() {
        let (email, checksum, _pk_bind, salt) = parse_wallet_id("bob@example.com/a3f7b2ff32").unwrap();
        assert_eq!(email, "bob@example.com");
        assert_eq!(checksum, "a3f7b2");
        assert_eq!(salt, "32");
    }
    
    #[test]
    fn test_parse_wallet_id_with_dashes() {
        let (email, checksum, _pk_bind, salt) = parse_wallet_id("bob@example.com/a3f7-b2ff-32").unwrap();
        assert_eq!(email, "bob@example.com");
        assert_eq!(checksum, "a3f7b2");
        assert_eq!(salt, "32");
    }
    
    #[test]
    fn test_parse_wallet_id_no_slash() {
        let result = parse_wallet_id("bob@example.com");
        assert!(matches!(result, Err(ValidationError::MalformedAddress)));
    }
    
    #[test]
    fn test_parse_wallet_id_no_at() {
        let result = parse_wallet_id("bobexample.com/a3f7b2ff32");
        assert!(matches!(result, Err(ValidationError::MalformedAddress)));
    }
    
    #[test]
    fn test_parse_wallet_id_wrong_length() {
        let result = parse_wallet_id("bob@example.com/a3f7b2"); // only 6 chars
        assert!(matches!(result, Err(ValidationError::MalformedAddress)));
    }
    
    #[test]
    fn test_extract_email() {
        assert_eq!(
            extract_email("bob@example.com/a3f7b2ff32").unwrap(),
            "bob@example.com"
        );
    }
    
    #[test]
    fn test_generate_and_validate() {
        let email = "alice@test.com";
        let salt = "42";
        
        let wallet_id = generate_wallet_id(email, salt, &[0u8; 32]).unwrap();
        
        // Should validate
        assert!(validate_wallet_id(&wallet_id).is_ok());
        
        // Extract email should work
        assert_eq!(extract_email(&wallet_id).unwrap(), email);
    }
    
    #[test]
    fn test_typo_detection() {
        // Generate valid wallet_id for correct email
        let wallet_id = generate_wallet_id("bob@example.net", "42", &[0u8; 32]).unwrap();
        assert!(validate_wallet_id(&wallet_id).is_ok());
        
        // Now simulate typo: "example" → "exmaple"
        let typo_wallet_id = wallet_id.replace("example", "exmaple");
        
        // Should REJECT - this is the anti-typo protection!
        assert!(matches!(
            validate_wallet_id(&typo_wallet_id),
            Err(ValidationError::InvalidWalletId)
        ));
    }
    
    #[test]
    fn test_different_salt_different_checksum() {
        let email = "bob@example.com";
        let wallet_id_1 = generate_wallet_id(email, "00", &[0u8; 32]).unwrap();
        let wallet_id_2 = generate_wallet_id(email, "01", &[0u8; 32]).unwrap();
        
        // Different salt should produce different wallet_ids
        assert_ne!(wallet_id_1, wallet_id_2);
        
        // But both should validate
        assert!(validate_wallet_id(&wallet_id_1).is_ok());
        assert!(validate_wallet_id(&wallet_id_2).is_ok());
    }
    
    // === C2 Security Tests: Normalization ===
    
    #[test]
    fn test_email_normalization_lowercase() {
        // "BOB@EXAMPLE.COM" should be normalized to "bob@example.com"
        let wallet_id = generate_wallet_id("BOB@EXAMPLE.COM", "42", &[0u8; 32]).unwrap();
        assert!(wallet_id.starts_with("bob@example.com/"));
        assert!(validate_wallet_id(&wallet_id).is_ok());
    }
    
    #[test]
    fn test_email_normalization_trim() {
        // "  bob@example.com  " should be normalized to "bob@example.com"
        let wallet_id = generate_wallet_id("  bob@example.com  ", "42", &[0u8; 32]).unwrap();
        assert!(wallet_id.starts_with("bob@example.com/"));
    }
    
    #[test]
    fn test_email_normalization_case_insensitive_checksum() {
        // "Bob@Example.COM" and "bob@example.com" should produce same checksum
        let wallet_id_upper = generate_wallet_id("Bob@Example.COM", "42", &[0u8; 32]).unwrap();
        let wallet_id_lower = generate_wallet_id("bob@example.com", "42", &[0u8; 32]).unwrap();
        assert_eq!(wallet_id_upper, wallet_id_lower);
    }
    
    #[test]
    fn test_reject_non_ascii_email() {
        // Cyrillic 'а' (U+0430) looks like Latin 'a' but is different!
        // This is a homoglyph attack
        let result = generate_wallet_id("аlice@test.com", "42", &[0u8; 32]); // Cyrillic а
        assert!(result.is_err());
    }
    
    #[test]
    fn test_reject_emoji_in_email() {
        let result = generate_wallet_id("bob😀@test.com", "42", &[0u8; 32]);
        assert!(result.is_err());
    }
    
    #[test]
    fn test_reject_chinese_in_email() {
        let result = generate_wallet_id("用户@test.com", "42", &[0u8; 32]);
        assert!(result.is_err());
    }

    // === YPX-007: Multi-address wallet tests ===

    #[test]
    fn test_generate_all_wallet_ids_returns_7() {
        let all = generate_all_wallet_ids("alice@test.com", "7f", &[0u8; 32]).unwrap();
        assert_eq!(all.len(), 7);
    }

    #[test]
    fn test_all_7_checksums_are_different() {
        let all = generate_all_wallet_ids("alice@test.com", "7f", &[0u8; 32]).unwrap();
        let checksums: Vec<&str> = all.iter().map(|(wid, _, _, _)| {
            let slash = wid.rfind('/').unwrap();
            &wid[slash + 1..slash + 7]
        }).collect();
        // All 7 checksums must be unique
        for i in 0..7 {
            for j in (i + 1)..7 {
                assert_ne!(checksums[i], checksums[j],
                    "Checksums {} and {} collide: {} == {}",
                    WALLET_ID_PARAMS[i].2, WALLET_ID_PARAMS[j].2,
                    checksums[i], checksums[j]);
            }
        }
    }

    #[test]
    fn test_all_7_share_same_salt() {
        let all = generate_all_wallet_ids("alice@test.com", "7f", &[0u8; 32]).unwrap();
        for (wid, _, _, name) in &all {
            assert!(wid.ends_with("7f"), "{} should end with salt '7f': {}", name, wid);
        }
    }

    #[test]
    fn test_extract_security_level_all_7() {
        let all = generate_all_wallet_ids("alice@test.com", "42", &[0u8; 32]).unwrap();
        for (wid, expected_k, expected_pt, name) in &all {
            let (k, pt) = extract_security_level(wid).unwrap();
            assert_eq!(k, *expected_k, "{}: k mismatch", name);
            assert_eq!(pt, *expected_pt, "{}: proof_type mismatch", name);
        }
    }

    #[test]
    fn test_extract_security_level_invalid_checksum() {
        // Valid hex but random checksum that won't match any combination
        let result = extract_security_level("alice@test.com/aabbccdd42");
        assert!(matches!(result, Err(ValidationError::InvalidWalletId)));
    }

    #[test]
    fn test_generate_wallet_id_defaults_to_standard() {
        let standard_direct = generate_wallet_id("alice@test.com", "42", &[0u8; 32]).unwrap();
        let all = generate_all_wallet_ids("alice@test.com", "42", &[0u8; 32]).unwrap();
        // generate_wallet_id defaults to Standard (k=3, dmap)
        let standard_from_all = &all[1]; // index 1 = Standard
        assert_eq!(standard_direct, standard_from_all.0);
    }

    #[test]
    fn test_sabr_overlap_values() {
        assert_eq!(sabr_overlap(0), 0);  // Ark: no validators
        assert_eq!(sabr_overlap(3), 2);  // Standard/A+: >50% of 3
        assert_eq!(sabr_overlap(4), 3);  // Secure/Secure+: >50% of 4
        assert_eq!(sabr_overlap(5), 3);  // AAA/AAA+: >50% of 5
    }

    #[test]
    fn test_validate_wallet_id_works_with_new_format() {
        // generate + validate round-trip must still work
        let all = generate_all_wallet_ids("bob@example.com", "ff", &[0u8; 32]).unwrap();
        for (wid, _, _, name) in &all {
            assert!(validate_wallet_id(wid).is_ok(), "{} should validate: {}", name, wid);
        }
    }

    #[test]
    fn test_typo_detection_new_format() {
        let all = generate_all_wallet_ids("bob@example.net", "42", &[0u8; 32]).unwrap();
        for (wid, _, _, name) in &all {
            let typo = wid.replace("example", "exmaple");
            assert!(matches!(
                validate_wallet_id(&typo),
                Err(ValidationError::InvalidWalletId)
            ), "{} should reject typo: {}", name, typo);
        }
    }

    /// Randomized: generate + extract round-trip for many emails × salts × all 7 tiers.
    #[test]
    fn test_random_emails_salts_all_tiers() {
        let emails = [
            "alice@example.com", "bob@example.net", "charlie.brown@test.org",
            "delta+tag@axiom.net", "echo_99@mail.co.jp", "foxtrot@x.io",
            "g@a.b", "hello.world@sub.domain.example.com",
            "user123@192.168.1.1", "z@z.zz",
        ];
        // Use a simple deterministic "random" salt set covering hex space
        let salts = ["00", "01", "42", "7f", "a3", "ff", "b9", "1e", "d0", "5c"];

        for email in &emails {
            for salt in &salts {
                let all = generate_all_wallet_ids(email, salt, &[0u8; 32]).unwrap();
                assert_eq!(all.len(), 7, "should produce 7 addresses for {}/{}", email, salt);

                for (wid, expected_k, expected_pt, name) in &all {
                    // Validate round-trip
                    assert!(validate_wallet_id(wid).is_ok(),
                        "{}/{} tier {} should validate: {}", email, salt, name, wid);

                    // Extract must return correct (k, proof_type)
                    let (k, pt) = extract_security_level(wid).unwrap();
                    assert_eq!(k, *expected_k,
                        "{}/{} tier {}: k mismatch (got {}, want {})", email, salt, name, k, expected_k);
                    assert_eq!(pt, *expected_pt,
                        "{}/{} tier {}: proof_type mismatch (got {}, want {})", email, salt, name, pt, expected_pt);
                }

                // All 7 checksums must be distinct
                let checksums: Vec<&str> = all.iter().map(|(wid, _, _, _)| {
                    let slash = wid.rfind('/').unwrap();
                    &wid[slash + 1..slash + 7]
                }).collect();
                for i in 0..7 {
                    for j in (i + 1)..7 {
                        assert_ne!(checksums[i], checksums[j],
                            "{}/{}: {} and {} collide", email, salt,
                            WALLET_ID_PARAMS[i].2, WALLET_ID_PARAMS[j].2);
                    }
                }
            }
        }
        // 10 emails × 10 salts × 7 tiers = 700 wallet_id round-trips
    }

    /// Randomized: tampered checksums are always rejected.
    #[test]
    fn test_random_tampered_checksums_rejected() {
        let emails = ["alice@a.com", "bob@b.org", "cc@d.net", "ee@ff.gg", "hh@ii.jj"];
        let salts = ["00", "42", "ff", "a1", "3b"];

        for email in &emails {
            for salt in &salts {
                let all = generate_all_wallet_ids(email, salt, &[0u8; 32]).unwrap();
                for (wid, _, _, name) in &all {
                    // Flip one hex char in checksum → must fail
                    let slash = wid.rfind('/').unwrap();
                    let mut tampered = wid.clone();
                    let byte_pos = slash + 1; // first char of checksum
                    let original = tampered.as_bytes()[byte_pos];
                    let flipped = if original == b'0' { b'1' } else { b'0' };
                    // Safety: replacing one ASCII hex char with another ASCII hex char
                    unsafe { tampered.as_bytes_mut()[byte_pos] = flipped; }
                    assert!(extract_security_level(&tampered).is_err(),
                        "{}/{} tier {}: tampered checksum should be rejected: {}",
                        email, salt, name, tampered);
                }
            }
        }
        // 5 emails × 5 salts × 7 tiers = 175 tamper checks
    }

    // === wallet_secret-based wallet_id tests ===

    #[test]
    fn test_generate_with_secret_roundtrip() {
        let secret = [0xAA; 32];
        let pk = [0xBB; 32];
        let wids = generate_all_wallet_ids_with_secret("alice@test.com", "00", &secret, &pk).unwrap();
        assert_eq!(wids.len(), 7);
        for (wid, k, pt, _name) in &wids {
            let (vk, vpt) = verify_wallet_id_with_secret(wid, &secret, &pk).unwrap();
            assert_eq!(vk, *k);
            assert_eq!(vpt, *pt);
        }
    }

    #[test]
    fn test_secret_binds_to_pk() {
        let secret = [0xAA; 32];
        let pk1 = [0xBB; 32];
        let pk2 = [0xCC; 32];
        let wid1 = generate_wallet_id_with_secret("alice@test.com", "00", &secret, &pk1).unwrap();
        let wid2 = generate_wallet_id_with_secret("alice@test.com", "00", &secret, &pk2).unwrap();
        assert_ne!(wid1, wid2, "different PKs must produce different wallet_ids");
    }

    #[test]
    fn test_wrong_secret_rejects() {
        let secret = [0xAA; 32];
        let wrong_secret = [0xFF; 32];
        let pk = [0xBB; 32];
        let wid = generate_wallet_id_with_secret("alice@test.com", "00", &secret, &pk).unwrap();
        assert!(verify_wallet_id_with_secret(&wid, &wrong_secret, &pk).is_err());
    }

    #[test]
    fn test_wrong_pk_rejects() {
        let secret = [0xAA; 32];
        let pk = [0xBB; 32];
        let wrong_pk = [0xCC; 32];
        let wid = generate_wallet_id_with_secret("alice@test.com", "00", &secret, &pk).unwrap();
        assert!(verify_wallet_id_with_secret(&wid, &secret, &wrong_pk).is_err());
    }

    // === Email change suffix (-XX) tests ===

    #[test]
    fn test_strip_email_change_suffix() {
        let (clean, n) = strip_email_change_suffix("alice@test.com/a3f7b2ff32-01");
        assert_eq!(clean, "alice@test.com/a3f7b2ff32");
        assert_eq!(n, Some(1));

        let (clean, n) = strip_email_change_suffix("alice@test.com/a3f7b2ff32-99");
        assert_eq!(clean, "alice@test.com/a3f7b2ff32");
        assert_eq!(n, Some(99));

        let (clean, n) = strip_email_change_suffix("alice@test.com/a3f7b2ff32");
        assert_eq!(clean, "alice@test.com/a3f7b2ff32");
        assert_eq!(n, None);
    }

    #[test]
    fn test_requires_receiver_address() {
        assert!(requires_receiver_address("alice@test.com/a3f7b2ff32-01"));
        assert!(requires_receiver_address("alice@test.com/a3f7b2ff32-05-P"));
        assert!(!requires_receiver_address("alice@test.com/a3f7b2ff32"));
        assert!(!requires_receiver_address("alice@test.com/a3f7b2ff32-P"));
    }

    #[test]
    fn test_email_change_suffix_validates() {
        // Generate a valid wallet_id, append -01 — should still validate
        let wid = generate_wallet_id("alice@test.com", "42", &[0u8; 32]).unwrap();
        let wid_changed = format!("{}-01", wid);
        assert!(validate_wallet_id(&wid_changed).is_ok(),
            "wallet_id with -01 suffix should validate: {}", wid_changed);
    }

    #[test]
    fn test_email_change_with_pgp_suffix() {
        let wid = generate_wallet_id("alice@test.com", "42", &[0u8; 32]).unwrap();
        let wid_both = format!("{}-01-P", wid);
        assert!(validate_wallet_id(&wid_both).is_ok(),
            "wallet_id with -01-P should validate: {}", wid_both);
        assert!(requires_receiver_address(&wid_both));
    }

    // ── FACT class isolation (Rule R1) ──────────────────────────────

    /// Build a valid wallet_id for the given email — `pk_bind` /
    /// checksum reproducibility doesn't matter for the class tests
    /// (they read the email part before the `/`), so we use a
    /// fixed zero pk and short salt.
    fn classed_wid(email: &str) -> String {
        format!("{}/aabbccdd42", email)
    }

    #[test]
    fn test_is_dev_wallet_recognises_axiom_internal_only() {
        // EXACT @axiom.internal domain → dev.
        assert!(is_dev_wallet(&classed_wid("developer@axiom.internal")));
        assert!(is_dev_wallet(&classed_wid("tester@axiom.internal")));
        // Case-insensitive on the domain.
        assert!(is_dev_wallet(&classed_wid("DEV@AXIOM.INTERNAL")));
        // Everything else → not dev.
        assert!(!is_dev_wallet(&classed_wid("alice@example.com")));
        assert!(!is_dev_wallet(&classed_wid("alice@axiom")));           // missing .internal
        assert!(!is_dev_wallet(&classed_wid("alice@axiom.com")));       // .com not .internal
        assert!(!is_dev_wallet(&classed_wid("alice@axiom.internal.com"))); // subdomain
        assert!(!is_dev_wallet(&classed_wid("alice@axiom-internal")));  // hyphen not dot
        assert!(!is_dev_wallet(&classed_wid("alice@myaxiom.internal"))); // prefix
    }

    #[test]
    fn test_check_domain_isolation_same_class_passes() {
        // public → public
        check_domain_isolation(
            &classed_wid("alice@example.com"),
            &classed_wid("bob@example.org"),
        ).expect("public -> public must pass R1");
        // dev → dev
        check_domain_isolation(
            &classed_wid("developer@axiom.internal"),
            &classed_wid("tester@axiom.internal"),
        ).expect("dev -> dev must pass R1");
    }

    #[test]
    fn test_check_domain_isolation_rejects_cross_class() {
        // public → dev
        let err1 = check_domain_isolation(
            &classed_wid("alice@example.com"),
            &classed_wid("developer@axiom.internal"),
        ).expect_err("public -> dev must be rejected");
        assert_eq!(err1, ValidationError::DomainMismatch);
        // dev → public (symmetric — no one-way valve, design §3)
        let err2 = check_domain_isolation(
            &classed_wid("developer@axiom.internal"),
            &classed_wid("alice@example.com"),
        ).expect_err("dev -> public must be rejected (symmetric R1)");
        assert_eq!(err2, ValidationError::DomainMismatch);
    }

    #[test]
    fn test_check_domain_isolation_protocol_addresses_exempt() {
        // Either class must be able to burn / pay fees / write deeds.
        check_domain_isolation(
            &classed_wid("alice@example.com"),
            crate::types::BURN_ADDRESS,
        ).expect("public -> BURN must pass R1");
        check_domain_isolation(
            &classed_wid("developer@axiom.internal"),
            crate::types::BURN_ADDRESS,
        ).expect("dev -> BURN must pass R1 (burning dev-AXC must remain possible)");
        check_domain_isolation(
            &classed_wid("alice@example.com"),
            crate::types::FEE_ADDRESS,
        ).expect("public -> FEE must pass R1");
        check_domain_isolation(
            &classed_wid("alice@example.com"),
            crate::types::DEED_ADDRESS,
        ).expect("public -> DEED must pass R1");
    }

    /// Decode entry points must NEVER panic on hostile / malformed input — a
    /// receiver_wallet_id inside a TX is attacker-controlled, so a UTF-8
    /// char-boundary slice that unwinds would crash Core (DoS). Every decoder
    /// must fail closed (Err / None / safe value), not panic. This pins the fix
    /// for `strip_email_change_suffix` byte-slicing a multi-byte tail and audits
    /// the sibling decoders.
    #[test]
    fn decoders_never_panic_on_hostile_input() {
        let hostile = [
            "",                       // empty
            "@",                      // bare separator
            "/",                      // bare slash
            "-P",                     // just an encryption suffix
            "--",                     // dashes
            "🙂@x.com/🙂",            // 4-byte emoji tail (the original repro)
            "🙂",                     // lone 4-byte char (len 4, tail mid-char at len-3)
            "x/🙂",                   // 4-byte tail after slash
            "café@x.com/déadbeef12",  // 2-byte accents (é) at various positions
            "a@b.com/abcdef012é",     // 2-byte char as the tail
            "x😀",                    // ASCII + 4-byte tail, len 5
            "ab🙂",                   // 2 ASCII + 4-byte, len-3 lands mid-emoji
            "@/-0",                   // mixed
            "alice@example.com/a3f7b2ff32-1🙂", // valid-ish prefix + emoji tail
            &"🙂".repeat(1000),       // very long multi-byte
            &"a".repeat(100_000),     // very long ASCII
            "bob@example.com/a3f7b2ff32-01", // a genuinely valid -XX suffix (must still parse)
        ];
        for w in hostile {
            // None of these may panic; results are don't-care (Err/None/value).
            let _ = strip_encryption_suffix(w);
            let _ = strip_email_change_suffix(w);
            let _ = requires_receiver_address(w);
            let _ = is_dev_wallet(w);
            let _ = parse_wallet_id(w);
            let _ = extract_email(w);
            let _ = extract_security_level(w);
        }
        // Targeted: the exact repro returns Err, not a panic.
        assert!(extract_security_level("🙂@x.com/🙂").is_err());
        // The multi-byte tail is not mistaken for a "-XX" suffix.
        let (clean, change) = strip_email_change_suffix("ab🙂");
        assert_eq!(clean, "ab🙂");
        assert_eq!(change, None);
        // A real "-01" suffix on a valid hex10 wallet still strips correctly.
        let (clean, change) = strip_email_change_suffix("bob@example.com/a3f7b2ff32-01");
        assert_eq!(clean, "bob@example.com/a3f7b2ff32");
        assert_eq!(change, Some(1));
    }
}

/// Generate wallet IDs for testing (prints to stdout)
/// Run with: cargo test gen_test_wallet_ids -- --nocapture
#[cfg(test)]
pub fn print_test_wallet_ids() {
    println!("\n# Valid wallet IDs with BLAKE3 checksums");
    println!("# Paste this into test-fixtures/generate_wallets.py");
    println!("VALID_WALLET_IDS = {{");
    for i in 0..100 {
        let email = format!("w{:03}@test.axiom", i);
        let salt = format!("{:02x}", i);
        let wallet_id = generate_wallet_id(&email, &salt, &[0u8; 32]).unwrap();
        println!("    {}: \"{}\",", i, wallet_id);
    }
    println!("}}");
}

/// Generate validator IDs for testing (prints to stdout)
/// Run with: cargo test gen_test_validator_ids -- --nocapture
#[cfg(test)]
pub fn print_test_validator_ids() {
    println!("\n# Valid validator IDs with BLAKE3 checksums");
    println!("# Paste this into test-fixtures/test_config.json");
    println!("VALID_VALIDATOR_IDS = {{");
    for i in 1..=6 {
        let email = format!("v{}@axiom.validators", i);
        let salt = format!("{:02x}", i);
        let validator_id = generate_wallet_id(&email, &salt, &[0u8; 32]).unwrap();
        let carrier = format!("mailto:v{}@axiom.validators", i);
        println!("    \"V{}\": {{", i);
        println!("        \"id\": \"{}\",", validator_id);
        println!("        \"carrier\": \"{}\",", carrier);
        println!("    }},");
    }
    println!("}}");
}

#[test]
fn gen_test_wallet_ids() {
    print_test_wallet_ids();
}

#[test]
fn gen_test_validator_ids() {
    print_test_validator_ids();
}
