//! AXIOM zkVM Methods
//!
//! This crate provides the compiled guest program (ELF) and its image ID.
//!
//! The image ID is a cryptographic hash of the guest program that uniquely
//! identifies it. All validators must use the same image ID to ensure
//! they're running the same Core.bin logic.
//!
//! # Usage
//!
//! ```rust,ignore
//! use axiom_zkvm_methods::{AXIOM_CORE_ELF, AXIOM_CORE_ID};
//!
//! // Use the ELF to run the guest
//! let receipt = prover.prove(env, AXIOM_CORE_ELF)?;
//!
//! // Verify using the image ID
//! receipt.verify(AXIOM_CORE_ID)?;
//! ```

// Include the generated methods
// This is generated by risc0-build in build.rs
include!(concat!(env!("OUT_DIR"), "/methods.rs"));
