//! §6c — print the ten GENESIS STAKE WALLET ids for `genesis_lockup_wallets.txt`,
//! for a fleet whose G1 ceremony predates the ceremony writing them itself.
//!
//! Derivation is the SDK's own (`wallet_id::default_salt` + `generate_wallet_id`)
//! over each validator's `config/ed25519.pub` — the certificate key — and the
//! `wallet_email` recorded in `core/genesis-ceremony.toml`. The G1 ceremony
//! (`lambda/src/bin/genesis_ceremony.rs`) writes the same list on the day; this
//! exists so the deployed fleet can be brought to the same state without a new
//! ceremony.
//!
//!   cargo run -q -p axiom-core-logic --example genesis_stake_ids -- \
//!       core/genesis-ceremony.toml <repo-root>
use std::{env, fs, path::Path};

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() != 3 {
        eprintln!("usage: genesis_stake_ids <genesis-ceremony.toml> <AXIOM_HOME>");
        std::process::exit(2);
    }
    let toml = fs::read_to_string(&args[1]).expect("read ceremony toml");
    let home = Path::new(&args[2]);
    // Minimal parse: [[validators]] blocks with `name = "..."` and `wallet_email = "..."`.
    let mut name: Option<String> = None;
    let mut email: Option<String> = None;
    let mut rows: Vec<(String, String)> = Vec::new();
    let flush = |name: &mut Option<String>, email: &mut Option<String>, rows: &mut Vec<(String, String)>| {
        if let (Some(n), Some(e)) = (name.take(), email.take()) { rows.push((n, e)); }
        *name = None; *email = None;
    };
    let mut in_validators = false;
    for line in toml.lines() {
        let t = line.trim();
        if t.starts_with('[') {
            flush(&mut name, &mut email, &mut rows);
            in_validators = t.starts_with("[[validators]]");
            continue;
        }
        if !in_validators { continue; }
        if let Some(v) = t.strip_prefix("name") { if let Some(q) = v.trim().strip_prefix('=') { name = Some(q.trim().trim_matches('"').to_string()); } }
        if let Some(v) = t.strip_prefix("wallet_email") { if let Some(q) = v.trim().strip_prefix('=') { email = Some(q.trim().trim_matches('"').to_string()); } }
    }
    flush(&mut name, &mut email, &mut rows);
    println!("# Genesis STAKE wallet ids — §6c. Generated by core/logic/examples/genesis_stake_ids.rs");
    println!("# from core/genesis-ceremony.toml wallet_email + each validator's config/ed25519.pub");
    println!("# (the certificate key). Columns: <wallet_id> <ed25519_pk_hex> — the KEY is the identity;");
    println!("# the id is only an address. The G1 ceremony writes this file itself on the day.");
    for (n, e) in &rows {
        let short = n.trim_start_matches("axiom-first-penguin-");
        let pub_path = home.join(format!("axiom-first-penguin-{short}")).join("config/ed25519.pub");
        let pk = match fs::read(&pub_path) {
            Ok(b) => b,
            Err(err) => { eprintln!("# skipped {n}: {} ({err})", pub_path.display()); continue; }
        };
        let pk_arr: [u8; 32] = pk.as_slice().try_into().expect("ed25519.pub must be 32 bytes");
        let salt = axiom_core_logic::wallet_id::default_salt(&pk_arr);
        let id = axiom_core_logic::wallet_id::generate_wallet_id(e, &salt, &pk_arr).expect("wallet id");
        println!("{id} {}", hex::encode(pk_arr));
    }
}
