//! Phase 1 of the Genesis Re-Domaining Ceremony
//! (`docs/AXIOM_OPS_GenesisReDomaining.md`).
//!
//! Re-derives the ten GENESIS STAKE wallet ids onto NEW, REAL email domains,
//! keeping each validator's Ed25519 key BYTE-IDENTICAL — so the opening balance
//! and opening state_id (both key-derived, `genesis.rs::genesis_opening_balance`
//! / `opening_state_id_for`) and every VBC (which binds keys + node_name, never
//! the email) are preserved. Only the wallet_id STRING changes, which flips the
//! class from dev (`@axiom`) to real and moves the CoreID.
//!
//! The salt is deterministic (`wallet_id::default_salt(pk)`), so the new id is
//! reproducible from (new_email, key) alone — no stored salt, no fleet access.
//! This is the SAME derivation `genesis_stake_ids.rs` and the G1 ceremony use.
//!
//! A validator's real domain is ANY non-dev domain — a genesis operator may use
//! `trustmesh.org` or its per-node domain; a third-party operator may use plain
//! `gmail.com` / `yahoo.com` / their own. "Real" == NOT `@axiom` / `@axiom.internal`.
//!
//! Usage (from src/):
//!   cargo run -q -p axiom-core-logic --example redomain_genesis_stake_ids -- \
//!       core/logic/genesis_lockup_wallets.txt redomain-map.txt [--write]
//!
//!   redomain-map.txt: one `<local-part> <new-email>` per line, e.g.
//!       validator_alpha    alpha@example.com
//!       validator_zeta     validator_zeta@zeta.example.org
//!   (`#` comments and blank lines ignored; local-part is the part before `@`
//!    in the CURRENT id, so `validator_alpha@axiom` is keyed by `validator_alpha`.)
//!
//! Without `--write` it PRINTS the new file + a verification table to stdout and
//! changes nothing (dry-run — the default). With `--write` it overwrites the
//! input `genesis_lockup_wallets.txt` (back it up first — the ceremony does).
//! Exit non-zero if ANY row fails a safety assertion.
use std::{collections::HashMap, env, fs, process::exit};

use axiom_core_logic::wallet_id::{default_salt, generate_wallet_id, is_dev_wallet};
use axiom_core_logic::genesis::genesis_opening_balance;

fn parse_lockup(text: &str) -> Vec<(String, [u8; 32])> {
    let mut out = Vec::new();
    for line in text.lines() {
        let t = line.trim();
        if t.is_empty() || t.starts_with('#') { continue; }
        let mut cols = t.split_whitespace();
        let id = cols.next().unwrap_or("").to_string();
        let key_hex = cols.next().unwrap_or("");
        if id.is_empty() || key_hex.is_empty() {
            eprintln!("FATAL: lockup line has no <id> <key_hex>: {t:?}");
            exit(2);
        }
        let bytes = (0..key_hex.len() / 2)
            .map(|i| u8::from_str_radix(&key_hex[i * 2..i * 2 + 2], 16)
                .unwrap_or_else(|_| { eprintln!("FATAL: key col not hex: {key_hex}"); exit(2); }))
            .collect::<Vec<u8>>();
        let key: [u8; 32] = bytes.as_slice().try_into()
            .unwrap_or_else(|_| { eprintln!("FATAL: key col not 32 bytes: {key_hex}"); exit(2); });
        out.push((id, key));
    }
    out
}

fn parse_map(text: &str) -> HashMap<String, String> {
    let mut m = HashMap::new();
    for line in text.lines() {
        let t = line.trim();
        if t.is_empty() || t.starts_with('#') { continue; }
        let mut cols = t.split_whitespace();
        let (k, v) = (cols.next().unwrap_or(""), cols.next().unwrap_or(""));
        if k.is_empty() || v.is_empty() {
            eprintln!("FATAL: map line has no <local-part> <new-email>: {t:?}");
            exit(2);
        }
        m.insert(k.to_string(), v.to_string());
    }
    m
}

/// local part of a wallet_id: `validator_alpha@axiom/2be5...` -> `validator_alpha`.
fn local_part(id: &str) -> &str {
    id.split('@').next().unwrap_or(id)
}

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() < 3 {
        eprintln!("usage: redomain_genesis_stake_ids <genesis_lockup_wallets.txt> <redomain-map.txt> [--write]");
        exit(2);
    }
    let lockup_path = &args[1];
    let map_path = &args[2];
    let write = args.iter().any(|a| a == "--write");

    let rows = parse_lockup(&fs::read_to_string(lockup_path).expect("read lockup"));
    let map = parse_map(&fs::read_to_string(map_path).expect("read map"));

    let mut new_file = String::new();
    new_file.push_str("# Genesis STAKE wallet ids — §6c, RE-DOMAINED to real accounts.\n");
    new_file.push_str("# Generated by core/logic/examples/redomain_genesis_stake_ids.rs\n");
    new_file.push_str("# Keys are BYTE-IDENTICAL to the pre-re-domaining file (the KEY is the\n");
    new_file.push_str("# identity; the id is only an address). Only the email domain moved\n");
    new_file.push_str("# @axiom -> a real domain, flipping the class dev -> real.\n");

    println!("{:<22} {:<34} {:<34} {:>10} {}", "local", "OLD id", "NEW id", "balance", "verdict");
    let mut failed = 0usize;
    for (old_id, key) in &rows {
        let lp = local_part(old_id).to_string();
        let new_email = match map.get(&lp) {
            Some(e) => e.clone(),
            None => { println!("{lp:<22} {old_id:<34} {:<34} {:>10} MISSING-MAP-ENTRY", "-", "-"); failed += 1; continue; }
        };
        // Re-derive with the SAME key + deterministic salt + the new real email.
        let salt = default_salt(key);
        let new_id = match generate_wallet_id(&new_email, &salt, key) {
            Ok(id) => id,
            Err(e) => { println!("{lp:<22} {old_id:<34} {:<34} {:>10} DERIVE-ERR:{e:?}", "-", "-"); failed += 1; continue; }
        };
        let bal = genesis_opening_balance(key);
        // Safety assertions — every one must hold or the row FAILS.
        let new_is_real = !is_dev_wallet(&new_id);
        let key_is_genesis_stake = bal > 0;               // recognised genesis stake key
        let ok = new_is_real && key_is_genesis_stake;
        let verdict = if !new_is_real { "FAIL: new id STILL dev".to_string() }
            else if !key_is_genesis_stake { "FAIL: key not a genesis stake (bal=0)".to_string() }
            else { "ok".to_string() };
        if !ok { failed += 1; }
        println!("{lp:<22} {old_id:<34} {new_id:<34} {bal:>10} {verdict}");
        new_file.push_str(&format!("{new_id} {}\n", hex::encode(key)));
    }

    if failed > 0 {
        eprintln!("\n✗ {failed} row(s) FAILED a safety assertion — NOTHING written.");
        exit(1);
    }
    // Cross-check: the key set is unchanged (same count, same keys) — economics preserved.
    println!("\n✓ {} rows re-domained; all NEW ids are real-class; every key preserved \
              (balance key-derived, unchanged).", rows.len());

    if write {
        fs::write(lockup_path, &new_file).expect("write lockup");
        eprintln!("✓ WROTE {lockup_path} (back it up before rebuild — the ceremony does).");
    } else {
        println!("\n----- new {lockup_path} (dry-run; pass --write to apply) -----");
        print!("{new_file}");
    }
}
